export const REMOVE_REPORT = "REMOVE_REPORT"
export const BAN_USER = "BAN_USER"
export const REMOVE_POST = "REMOVE_POST"
export const ADMIN_LOG_IN = "ADMIN_LOG_IN"
export const ADMIN_GET_ITEMS = "ADMIN_GET_ITEMS"
export const ADMIN_LOG_IN_SUCCESS = "ADMIN_LOG_IN_SUCCESS";
export const ADMIN_GET_REPORT_ITEMS_SUCCESS = "ADMIN_GET_REPORT_ITEMS_SUCCESS"
export const ADMIN_LOG_IN_FAILURE = "ADMIN_LOG_IN_FAILURE"
