export const LOG_IN = "LOG_IN"
export const LOG_OUT = "LOG_OUT"
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS"
export const LOG_IN_FAILURE = "LOG_IN_FAILURE"
export const CHANGE_PASSWORD = "CHANGE_PASSWORD"