export const GET_POSTS = "GET_POSTS";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_REVIEWS = "GET_REVIEWS";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILURE = "GET_USER_INFO_FAILURE";
